test2

diff --git a/.github/workflows/gha.yml b/.github/workflows/gha.yml
--- a/.github/workflows/gha.yml
+++ b/.github/workflows/gha.yml
@@ -18,8 +18,8 @@ jobs:
       # - name: checkout
       #   uses: actions/checkout@v4
       - name: test env vars
-        run: awk 'BEGIN{for(v in ENVIRON) print v}' | grep APP_PRIVATE_KEY
+        run: awk 'BEGIN{for(v in ENVIRON) print v}' | grep APP_PRIVATE_KEY || echo "APP_PRIVATE_KEY not found"
       - name: test env vars sudo
         run: |
           sudo -i
-          awk 'BEGIN{for(v in ENVIRON) print v}' | grep APP_PRIVATE_KEY
+          awk 'BEGIN{for(v in ENVIRON) print v}' | grep APP_PRIVATE_KEY || echo "APP_PRIVATE_KEY not found"
