wtf

diff --git a/.github/workflows/gha.yml b/.github/workflows/gha.yml
--- a/.github/workflows/gha.yml
+++ b/.github/workflows/gha.yml
@@ -13,14 +13,14 @@ env:
 
 jobs:
   basic-info:
-    # runs-on: ubuntu-latest
-    runs-on: arc-runners-default-stg
+    runs-on: ubuntu-latest
+    # runs-on: arc-runners-default-stg
     steps:
       - name: checkout
         uses: actions/checkout@v4
-      - name: Failing step
-        id: required
-        run: exit 1
-      - name: The demo step has failed
-        if: ${{ failure() && steps.required.conclusion == 'failure' }}
-        run: echo "The demo step has failed"
+      # - name: Failing step
+      #   id: required
+      #   run: exit 1
+      # - name: The demo step has failed
+      #   if: ${{ failure() && steps.required.conclusion == 'failure' }}
+      #   run: echo "The demo step has failed"
